runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080
  GCS_PROJECT_ID: your-project-id
  GCS_BUCKET_NAME: wizard-prod-media-your-unique-id
  EMAIL_SERVICE: sendgrid
  EMAIL_FROM: noreply@yourdomain.com
  CORS_ORIGIN: https://yourdomain.com,https://www.yourdomain.com
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  MAX_FILE_SIZE: "10485760"
  JWT_EXPIRES_IN: 15m
  JWT_REFRESH_EXPIRES_IN: 30d

# Use Secret Manager for sensitive data
secret_environment_variables:
  - key: DATABASE_URL
    secret: DATABASE_URL
  - key: JWT_SECRET
    secret: JWT_SECRET
  - key: JWT_REFRESH_SECRET
    secret: JWT_REFRESH_SECRET
  - key: EMAIL_API_KEY
    secret: EMAIL_API_KEY

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Instance configuration
instance_class: F2

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Skip files to reduce deployment size
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.env$
  - ^(.*/)?\.env\.*
  - ^(.*/)?test/.*$
  - ^(.*/)?tests/.*$
  - ^(.*/)?\.nyc_output/.*$
  - ^(.*/)?coverage/.*$
  - ^(.*/)?\.coverage/.*$
  - ^(.*/)?dist/.*$
  - ^(.*/)?build/.*$
  - ^(.*/)?*.log$
